config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/about', to: 'home#about'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/complete_task', to: 'tasks#complete'

  get '/admin/:id/edit', to: 'users#admin_edit'

  resources :details, only: [:create, :destroy, :update]
  resources :comments, only: [:create, :destroy]
  resource :user, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
  
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_many :details, dependent: :destroy
  has_many :comments, dependent: :destroy
  default_scope -> { order(:scheduled_date) }
  validates :user_id, presence: true
  validates :title, presence: true

  def self.search(complete, search, no_schedule, working)
    result = Task.all
    result = result.where.not(status: 2).all if complete.nil?
    result = result.where('title LIKE ?', "%#{search}%").all if search
    result = result.where.not(scheduled_date: nil).all if no_schedule
    result = result.where(status: 1).all if working
    result
  end

  def self.complete_search(over, no_schedule, search)
    result = Task.where(status: 2).reorder(completion_date: :desc).all
    result = result.where(["scheduled_date < completion_date"]).all if over
    result = result.where.not(scheduled_date: nil).all if no_schedule
    result = result.where('title LIKE ?', "%#{search}%").all if search
    result
  end

  def self.aggregate
    today = Date.today
    day = today.prev_month
    day_data = {}
    while day <= today do
      day_data.store(day, Task.where("Date(created_at) <= ?", day).count)
      day += 1
    end
    day_data
  end

  def self.complete_aggregate
    today = Date.today
    day = today.prev_month
    day_data = {}
    while day <= today do
      day_data.store(day, Task.where("Date(completion_date) <= ?", day).count)
      day += 1
    end
    day_data
  end

  def self.task_count
    Task.where(created_at: Time.zone.now.ago(1.month)..Time.zone.now).count
  end

  def self.complete_count
    Task.where(completion_date: Time.zone.now.ago(1.month)..Time.zone.now).count
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def show
    @task = current_user.tasks.find_by(id: params[:id])
    @details_count = @task.details
    @details = @task.details.search(
      params[:complete], params[:search], params[:not_work], params[:working]).
      page(params[:page])
    @detail = @task.details.build
    @comments = @task.comments
    @comment = @task.comments.build
    @not_work_data = @details_count.where(status: 0).count
    @working_data = @details_count.where(status: 1).count
    @complete_data = @details_count.where(status: 2).count
    @chart_data = [['未作業', @not_work_data], ['作業中', @working_data], ['完了', @complete_data]]
    @complete_check = params[:complete]
    @not_work_check = params[:not_work]
    @working_check = params[:working]
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "タスクを登録しました"
      redirect_to task_path(@task)
    else
      render 'new'
    end
  end

  def edit
    @task = current_user.tasks.find_by(id: params[:id])
  end

  def update
    @task = current_user.tasks.find_by(id: params[:id])
    if @task.update(task_params)
      flash[:success] = "タスク情報を更新しました。"
      redirect_to task_path(@task)
    else
      render 'edit'
    end
  end

  def destroy
    current_user.tasks.find_by(id: params[:id]).destroy
    flash[:success] = "タスクを削除しました"
    redirect_to root_path
  end

  def complete
    @tasks = current_user.tasks.complete_search(
        params[:over], params[:no_schedule], params[:search]).page(params[:page])
    @limit_over =  current_user.tasks.where(["scheduled_date < completion_date"]).count
    @date_before = current_user.tasks.where(["scheduled_date > completion_date"]).count
    @scheduled = current_user.tasks.where(["scheduled_date = completion_date"]).count
    @chart_data = [['予定日完了', @scheduled], ['予定前完了', @date_before], ['予定超過', @limit_over]]
    @limit_check = params[:no_schedule]
    @over_check = params[:over]
  end

  private

    def task_params
      params.require(:task).permit(:title, :status, :completion_date, :scheduled_date, :send_mail)
    end

    def correct_user
      @task = current_user.tasks.find_by(id: params[:id])
      redirect_to root_url if @task.nil?
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_comment_form.html.erb
<%= form_for @comment, remote: true do |f| %>
  <%= hidden_field_tag :task_id, @task.id %>
  <%= f.label :body, 'コメント投稿' %>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/tasks/_task_form.html.erb
<%= form_for @task do |f| %>
<% if @task.errors.any? %>
  <ul class="alert">
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <ul class="alert" id="hidden">
    <li>予定日を過ぎています。</li>
  </ul>
  <%= f.label :scheduled_date %>
  <%= f.date_field :scheduled_date %>

  <% if current_user.email == "" || current_user.email.nil? %>
    <p>
      メールアドレスを登録すると、メール通知機能を使用できます。<br>
      <%= link_to "メールアドレスを登録", edit_user_path %>
    </p>
  <% else %>
    <p>
      <%= f.check_box :send_mail %>
      <%= f.label :send_mail, '通知メールを送信する。' %>
    </p>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/tasks/complete.html.erb
<% provide(:title, "完了済みタスク") %>
  <h1><%= yield(:title) %></h1>
  <aside class="user_info">
    <%= render 'shared/user_info' %>
    <p>完了数 ： <%= @tasks.count %></p>
    <p>予定日を超過したタスク : <%= @limit_over %></p>
    <p>予定日前に完了したタスク ： <%= @date_before %></p>
    <p>予定日に完了したタスク ： <%= @scheduled %></p>
    <%= pie_chart @chart_data %>
  </aside>

  <section class="task_area">
    <%= form_tag complete_task_path, method: :get, class: "search" do %>
      <%= check_box_tag :over, params[:over], @over_check %><%= label_tag :over, "予定日超過タスク" %>
      <%= check_box_tag :no_schedule, params[:no_schedule], @limit_check %><%= label_tag :no_schedule, "予定日のないタスクを表示しない" %><br>
      <%= label_tag :search, "タスク名" %> <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "検索", name: :nil %>
    <% end %>
    <table>
    <colgroup>
    <colgroup span="2" class="schedule">
      <tr>
        <th>タスク名</th><th>予定日</th><th>完了日</th>
      </tr>
      <% if @tasks.any? %>
        <% @tasks.each do |task| %>
          <tr id="task-<%= task.id %>">
            <td>
              <%= link_to task.title, task_path(task) %>
            </td>
            <td>
              <%= task.scheduled_date %>
            </td>
            <td>
              <%= task.completion_date %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
    <%= paginate @tasks %>
  </section>

app/views/tasks/edit.html.erb
<% provide(:title, "タスク情報更新") %>
<%= render "task_form" %>

app/views/tasks/new.html.erb
<% provide(:title, "タスク作成") %>
<%= render 'task_form'%>

app/views/tasks/show.html.erb
<% provide(:title, @task.title )%>
<h1><%= @task.title %></h1>
<main class="task_detail">
  <%= render 'details/detail_user_info' %>
  <section class="task_area">
    <ul class="alert" id="hidden">
      <li>タスク内容を入力してください</li>
    </ul>
    <%= form_for @detail do |f| %>
      <h3 class="task_form">タスク内容登録</h3>
      <%= f.label :content %>
      <%= f.text_field :content %>

      <%= hidden_field_tag :task_id, @task.id %>

      <%= f.submit %>
    <% end %>

    <%= render 'details/detail_table' %>
  </section>
</main>
    <h2 class="comment_title">コメント</h2>
    <%= render 'comments/comment' %>
    <%= render 'comment_form' %>