config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/about', to: 'home#about'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/complete_task', to: 'tasks#complete'

  get '/admin/:id/edit', to: 'users#admin_edit'

  resources :details, only: [:create, :destroy, :update]
  resources :comments, only: [:create, :destroy]
  resource :user, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      @tasks = current_user.tasks.search(
        params[:complete], params[:search], params[:no_schedule], params[:working]).page(params[:page])
      @complete_count = current_user.tasks.where(status: 2).count
      @limit_over_task = current_user.tasks.where(["scheduled_date < ?", Date.today])
        .where.not(status: 2).count
      @not_work_task = current_user.tasks.where(status: 0).count
      @working_task = current_user.tasks.where(status: 1).count
      @chart_data = [['未作業', @not_work_task], ['作業中', @working_task], ['完了', @complete_count]]
      @complete_check = params[:complete]
      @limit_check = params[:no_schedule]
      @working_check = params[:working]
    end
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_task.html.erb
<ul class="task_menu">
  <li><%= link_to "タスクを追加する", new_task_path %></li>
  <li><%= link_to "完了済みタスク", 'complete_task' %></li>
</ul>
<%= form_tag root_path, method: :get, class: "search" do %>
  <%= check_box_tag :complete, params[:complete], @complete_check %><%= label_tag :complete, "完了済タスクを表示する" %>
  <%= check_box_tag :no_schedule, params[:no_schedule], @limit_check %><%= label_tag :no_schedule, "予定日のないタスクを表示しない" %>
  <%= check_box_tag :working, params[:working], @working_check %><%= label_tag :working, "作業中タスクのみ表示" %><br>
  <%= label_tag :search, "タスク名" %> <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "検索", name: :nil %>
<% end %>
<table>
<colgroup>
<colgroup class="schedule">
<colgroup class="status">
<colgroup class="send-mail">
  <tr>
    <th>タスク名</th><th>予定日</th><th>ステータス</th><th>メール通知</th>
  </tr>
  <% if @tasks.any? %>
    <% @tasks.each do |task| %>
      <tr id="task-<%= task.id %>" class="<% if task.status == 2 %>complete<% elsif !task.scheduled_date.nil? %><% if task.scheduled_date < Date.today %>limit<% end %><% end %>">
        <td>
          <%= link_to task.title, task_path(task) %>
        </td>
        <td>
          <%= task.scheduled_date %>
        </td>
        <td>
          <% if task.status == 0 %>
            未作業
          <% elsif task.status == 1 %>
            作業中
          <% else %>
            完了
          <% end %>
        </td>
        <td>
          <% if task.send_mail %>
            ○
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= paginate @tasks %>

app/views/home/_user_info_home.html.erb
<%= render 'shared/user_info' %>
<p>タスク数 ： <%= @current_user.tasks_count %></p>
<p>未作業数 ： <%= @not_work_task %>
<p>作業中数 ： <%= @working_task %>
<p>完了数 ： <%= @complete_count %></p>
<p>予定日超過タスク ： <%= @limit_over_task %></p>
<p>達成率 ： <%= format("%.2f", achievement_rate) %>%</p>
<%= pie_chart @chart_data, animation: { duration: 2000, easing: 'linear'} %>

app/views/home/about.html.erb
<% provide(:title, 'Todoアプリについて')%>
<h1>Todoアプリについて</h1>
<p>勉強のために作ってみたサイトです。</p>
<h2>使い方</h2>
<h3>タスク</h3>
<ul class="about">
  <li>ログインするとタスク一覧ページが表示されます。</li>
  <li>タスクを追加するをクリックしてタスク追加フォームページへ</li>
  <li>タスク名と予定日を指定できます。<br>
    （※）タスク名は必須ですが、予定日はなくて構いません<br>
    （※）IEでは予定日をカレンダーから選ぶことができません。手動で入力する必要があります。<br>
    （※）メールアドレスを登録していると、通知メールを送信するチェックボックスが表示され、チェックを入れると完了していなかった場合予定日の朝8時ごろに通知メールが届きます。
  </li>
  <li>タスク内容ページが表示されるので、上部のタスク内容登録フォームにタスク内容を入力し、登録するボタンを押す。<br>
    （※）タスクを追加したら、タスク内容を必ず追加してください。<br>
    （※）タスク内容ページには任意のコメントをつけることができます。
  </li>
  <li>タスク内容が追加されます。作業に入ったり、作業が終わったら、ステータス欄のセレクトボックスでステータスを変更します。<br>
    （※）このステータス変更で、タスク自体のステータスが自動的に変更されます。
  </li>
  <li>タスクが完了すると、完了済みタスクにタスクが追加されます。</li>
  <li>予定日を過ぎたタスクは背景色が赤色になり、強調表示されます。</li>
</ul>

<h3>ユーザー設定</h3>
<ul class="about">
  <li>ヘッダーメニューのユーザー名をクリックすると、1ヶ月間の簡単なタスク集計が見られ、ユーザー情報更新、ユーザー削除が行えます。</li>
  <li>ユーザー情報更新では、ユーザー名、パスワードの変更に加え、メールアドレスの登録と、プロフィール画像、背景画像のアップロードができます。</li>
</ul>

<h3>その他不明点等</h3>
<ul>
  <li>管理者に直接問い合わせてください。<br>
    （※）パスワードを忘れた場合はユーザー名を教えてくれれば、パスワードを再設定します。
  </li>
</ul>

app/views/home/index.html.erb
  <% if logged_in? %>
    <h1>タスク一覧</h1>
    <aside class="user_info">
      <%= render 'user_info_home' %>
    </aside>
    <section class="task_area">
      <%= render 'task' %>
    </section>
  <% else %>
    <h1>Todoアプリへようこそ</h1>
    <p class="sign-in"><%= link_to('新規登録', new_user_path) %></p>
  <% end %>